"""
VTOL Hover Thrust Analysis Subsystem

Purpose:
    Defines the `HoverThrustAnalysis` class capturing thrust margins.
"""

from dataclasses import dataclass, field
from typing import Any, Dict


@dataclass(slots=True)
class HoverThrustAnalysis:
    """
    Rotor thrust margins at ISA hover altitude.

    Attributes:
        required_hover_thrust_n (float): Hover thrust required to balance weight.
        available_hover_thrust_n (float): Peak thrust generated by vertical lift rotors.
        thrust_to_weight_ratio (float): Ratio of available thrust to aircraft weight.
        thrust_margin_n (float): Reserve thrust margin.
        metadata (Dict[str, Any]): Intermediate thrust calculations.
    """

    required_hover_thrust_n: float
    available_hover_thrust_n: float
    thrust_to_weight_ratio: float
    thrust_margin_n: float
    metadata: Dict[str, Any] = field(default_factory=dict)
