"""
Studio package for Torq Wings Design Studio Phase 5.3 Aircraft Design Framework.
"""

from backend.design.studio.design_exception import (
    StudioDesignException,
    WorkflowExecutionError,
    StageTransitionError,
    SessionNotFoundError,
)
from backend.design.studio.design_session import DesignSession
from backend.design.studio.design_artifact import DesignArtifact
from backend.design.studio.design_result import DesignResult
from backend.design.studio.design_stage_manager import DesignStageManager
from backend.design.studio.design_workflow import DesignWorkflow
from backend.design.studio.design_studio import DesignStudio
from backend.design.studio.workflow import (
    WorkflowEngineException,
    StageExecutionError,
    StageNotFoundError,
    FatalWorkflowError,
    RecoverableWorkflowError,
    RetryableWorkflowError,
    WorkflowStageResult,
    WorkflowStage,
    WorkflowExecutor,
    WorkflowRegistry,
    WorkflowPipeline,
    WorkflowEngine,
)
from backend.design.studio.stages import (
    StageCategory,
    StageContext,
    StageResult,
    DesignStage,
    StageValidator,
    StageValidationError,
    StageRegistry,
    DuplicateStageRegistrationError,
    StageFactory,
)
from backend.design.studio.artifacts import (
    ArtifactCategory,
    ArtifactVersion,
    ArtifactMetadata,
    EngineeringArtifact,
    ArtifactFactory,
    ArtifactRegistry,
    ArtifactRepository,
    ArtifactNotFoundError,
    ArtifactValidator,
    ArtifactValidationError,
    ArtifactExporter,
)
from backend.design.studio.reports import (
    ReportSection,
    EngineeringReport,
    ReportTemplate,
    DroneReportTemplate,
    FixedWingReportTemplate,
    VTOLReportTemplate,
    EngineeringSummaryTemplate,
    ReportBuilder,
    ReportValidator,
    ReportValidationError,
    ReportExporter,
    JSONReportExporter,
    MarkdownReportExporter,
    HTMLReportExporter,
    ReportRegistry,
    ReportPipeline,
    ReportGenerator,
)
from backend.design.studio.persistence import (
    SessionSnapshot,
    SessionCheckpoint,
    SessionHistory,
    SessionSerializer,
    SessionValidator,
    SessionValidationError,
    DesignSessionRepository,
    SessionRecovery,
    SessionExporter,
    SessionImporter,
    SessionImportError,
    DesignSessionManager,
)

__all__ = [
    "StudioDesignException",
    "WorkflowExecutionError",
    "StageTransitionError",
    "SessionNotFoundError",
    "DesignSession",
    "DesignArtifact",
    "DesignResult",
    "DesignStageManager",
    "DesignWorkflow",
    "DesignStudio",
    "WorkflowEngineException",
    "StageExecutionError",
    "StageNotFoundError",
    "FatalWorkflowError",
    "RecoverableWorkflowError",
    "RetryableWorkflowError",
    "WorkflowStageResult",
    "WorkflowStage",
    "WorkflowExecutor",
    "WorkflowRegistry",
    "WorkflowPipeline",
    "WorkflowEngine",
    "StageCategory",
    "StageContext",
    "StageResult",
    "DesignStage",
    "StageValidator",
    "StageValidationError",
    "StageRegistry",
    "DuplicateStageRegistrationError",
    "StageFactory",
    "ArtifactCategory",
    "ArtifactVersion",
    "ArtifactMetadata",
    "EngineeringArtifact",
    "ArtifactFactory",
    "ArtifactRegistry",
    "ArtifactRepository",
    "ArtifactNotFoundError",
    "ArtifactValidator",
    "ArtifactValidationError",
    "ArtifactExporter",
    "ReportSection",
    "EngineeringReport",
    "ReportTemplate",
    "DroneReportTemplate",
    "FixedWingReportTemplate",
    "VTOLReportTemplate",
    "EngineeringSummaryTemplate",
    "ReportBuilder",
    "ReportValidator",
    "ReportValidationError",
    "ReportExporter",
    "JSONReportExporter",
    "MarkdownReportExporter",
    "HTMLReportExporter",
    "ReportRegistry",
    "ReportPipeline",
    "ReportGenerator",
    "SessionSnapshot",
    "SessionCheckpoint",
    "SessionHistory",
    "SessionSerializer",
    "SessionValidator",
    "SessionValidationError",
    "DesignSessionRepository",
    "SessionRecovery",
    "SessionExporter",
    "SessionImporter",
    "SessionImportError",
    "DesignSessionManager",
]
