"""
Components package for Torq Wings Design Studio Phase 5.2 Universal Component Selection Framework.
"""

from backend.design.components.component_category import ComponentCategory
from backend.design.components.component_selection_request import ComponentSelectionRequest
from backend.design.components.component_candidate import ComponentCandidate
from backend.design.components.component_selection_result import ComponentSelectionResult
from backend.design.components.component_repository import ComponentRepository
from backend.design.components.component_selector import ComponentSelector, DefaultComponentSelector
from backend.design.components.component_selection_pipeline import ComponentSelectionPipeline
from backend.design.components.compatibility import (
    CompatibilityStatus,
    CompatibilitySeverity,
    CompatibilityIssue,
    CompatibilityResult,
    CompatibilityRule,
    MotorESCCompatibilityRule,
    MotorPropellerCompatibilityRule,
    BatteryESCCompatibilityRule,
    BatteryMotorCompatibilityRule,
    FramePropellerCompatibilityRule,
    CompatibilityRegistry,
    CompatibilityPipeline,
    CompatibilityEngine,
)
from backend.design.components.constraints import (
    ConstraintStatus,
    ConstraintSeverity,
    ConstraintIssue,
    ConstraintResult,
    ConstraintRule,
    PayloadConstraintRule,
    MaximumTakeoffWeightConstraintRule,
    BudgetConstraintRule,
    FlightTimeConstraintRule,
    RangeConstraintRule,
    ThrustToWeightConstraintRule,
    ConstraintRegistry,
    ConstraintPipeline,
    ConstraintEngine,
)
from backend.design.components.scoring import (
    ScoreCategory,
    ScoreWeight,
    ScoreBreakdown,
    EngineeringScore,
    ScoringRule,
    PayloadScoreRule,
    EnduranceScoreRule,
    RangeScoreRule,
    CostScoreRule,
    WeightScoreRule,
    SafetyScoreRule,
    ScoringRegistry,
    ScoringPipeline,
    ScoringEngine,
)
from backend.design.components.ranking import (
    RankingCandidate,
    RankingResult,
    TieBreaker,
    RankingStrategy,
    HighestScoreStrategy,
    BalancedStrategy,
    LowestCostStrategy,
    MaximumEnduranceStrategy,
    HighestPayloadStrategy,
    RankingRegistry,
    RankingPipeline,
    RankingEngine,
)
from backend.design.components.optimization import (
    OptimizationGoal,
    OptimizationCandidate,
    OptimizationIteration,
    OptimizationResult,
    OptimizationStopCondition,
    OptimizationStrategy,
    GreedyOptimizationStrategy,
    HillClimbingStrategy,
    OptimizationRegistry,
    OptimizationPipeline,
    OptimizationEngine,
)

__all__ = [
    "ComponentCategory",
    "ComponentSelectionRequest",
    "ComponentCandidate",
    "ComponentSelectionResult",
    "ComponentRepository",
    "ComponentSelector",
    "DefaultComponentSelector",
    "ComponentSelectionPipeline",
    "CompatibilityStatus",
    "CompatibilitySeverity",
    "CompatibilityIssue",
    "CompatibilityResult",
    "CompatibilityRule",
    "MotorESCCompatibilityRule",
    "MotorPropellerCompatibilityRule",
    "BatteryESCCompatibilityRule",
    "BatteryMotorCompatibilityRule",
    "FramePropellerCompatibilityRule",
    "CompatibilityRegistry",
    "CompatibilityPipeline",
    "CompatibilityEngine",
    "ConstraintStatus",
    "ConstraintSeverity",
    "ConstraintIssue",
    "ConstraintResult",
    "ConstraintRule",
    "PayloadConstraintRule",
    "MaximumTakeoffWeightConstraintRule",
    "BudgetConstraintRule",
    "FlightTimeConstraintRule",
    "RangeConstraintRule",
    "ThrustToWeightConstraintRule",
    "ConstraintRegistry",
    "ConstraintPipeline",
    "ConstraintEngine",
    "ScoreCategory",
    "ScoreWeight",
    "ScoreBreakdown",
    "EngineeringScore",
    "ScoringRule",
    "PayloadScoreRule",
    "EnduranceScoreRule",
    "RangeScoreRule",
    "CostScoreRule",
    "WeightScoreRule",
    "SafetyScoreRule",
    "ScoringRegistry",
    "ScoringPipeline",
    "ScoringEngine",
    "RankingCandidate",
    "RankingResult",
    "TieBreaker",
    "RankingStrategy",
    "HighestScoreStrategy",
    "BalancedStrategy",
    "LowestCostStrategy",
    "MaximumEnduranceStrategy",
    "HighestPayloadStrategy",
    "RankingRegistry",
    "RankingPipeline",
    "RankingEngine",
    "OptimizationGoal",
    "OptimizationCandidate",
    "OptimizationIteration",
    "OptimizationResult",
    "OptimizationStopCondition",
    "OptimizationStrategy",
    "GreedyOptimizationStrategy",
    "HillClimbingStrategy",
    "OptimizationRegistry",
    "OptimizationPipeline",
    "OptimizationEngine",
]
