# backend/design/drone/report/report_builder.py
"""ReportBuilder coordinates the construction of a full engineering report.

It delegates the heavy lifting to a concrete :class:`ReportStrategy` but also
adds universal sections such as cover page, revision history and table of
contents.  The builder is deliberately lightweight – the actual content of each
section is provided by dedicated helper modules (e.g. ``executive_summary``).
"""

from __future__ import annotations

from typing import Any

from .report_result import ReportResult
from .report_strategy import ReportStrategy

# Section helper imports – each returns a markdown snippet.
from .executive_summary import build_executive_summary
from .design_summary import build_design_summary
from .engineering_summary import build_engineering_summary
from .performance_summary import build_performance_summary
from .verification_summary import build_verification_summary
from .optimization_summary import build_optimization_summary
from .manufacturing_summary import build_manufacturing_summary
from .cad_summary import build_cad_summary
from .appendix_builder import build_appendix


class ReportBuilder:
    """Orchestrates report creation using a strategy and section builders.

    The workflow is:
    1. Let the strategy produce the core technical sections.
    2. Enrich the :class:`ReportResult` with universal sections.
    """

    def __init__(self, strategy: ReportStrategy) -> None:
        self._strategy = strategy

    def build(self, snapshot: Any) -> ReportResult:
        # Strategy builds its own ReportResult (may already contain some sections).
        result: ReportResult = self._strategy.build_report(snapshot)

        # Add universal sections if they are not already present.
        # Cover page, revision history and TOC are represented as simple strings.
        # In a full implementation these would be generated from metadata.
        result.report = "# Cover Page\n\n*Generated by Torq Wings Design Studio*\n\n" + result.report
        result.report += "\n\n---\n\n# Revision History\n\n*Version 1.0 – Initial generation*\n\n---\n\n# Table of Contents\n\n*Generated automatically*\n\n---\n\n"

        # Populate executive summary and other high‑level sections using helpers.
        if not result.executive_summary:
            result.executive_summary = build_executive_summary(snapshot)
        if "Design Summary" not in result.technical_sections:
            result.add_section("Design Summary", build_design_summary(snapshot))
        if "Engineering Summary" not in result.technical_sections:
            result.add_section("Engineering Summary", build_engineering_summary(snapshot))
        if "Performance Summary" not in result.technical_sections:
            result.add_section("Performance Summary", build_performance_summary(snapshot))
        if "Verification Summary" not in result.technical_sections:
            result.add_section("Verification Summary", build_verification_summary(snapshot))
        if "Optimization Summary" not in result.technical_sections:
            result.add_section("Optimization Summary", build_optimization_summary(snapshot))
        if "Manufacturing Summary" not in result.technical_sections:
            result.add_section("Manufacturing Summary", build_manufacturing_summary(snapshot))
        if "CAD Summary" not in result.technical_sections:
            result.add_section("CAD Summary", build_cad_summary(snapshot))

        # Appendices – for demo we add one generic appendix.
        result.add_appendix(build_appendix(snapshot))

        # Assemble the full markdown report by concatenating sections in order.
        # In a real system we would respect the exact ordering from the spec.
        sections = [result.report]
        sections.append(result.executive_summary)
        for name, content in result.technical_sections.items():
            sections.append(f"## {name}\n\n{content}")
        if result.appendices:
            sections.append("## Appendices\n\n" + "\n\n---\n\n".join(result.appendices))
        result.report = "\n\n".join(sections)

        # Populate basic metadata.
        result.set_metadata(
            generated_at="{{TIMESTAMP}}",  # placeholder – will be replaced at runtime
            version="1.0",
            revision="A",
        )

        return result
