"""
Torq Wings Phase 13 Final Design Assembly & Universal Entry Package.
"""

from backend.design.assembly.final_design_contract import (
    FinalAircraftDesign,
    AircraftClass,
    OverallDesignStatus,
    RequirementTraceabilityItem,
    CoordinateSystemContract,
    GeometryContract,
    WingGeometryContract,
    FuselageGeometryContract,
    BoomGeometryContract,
    TailGeometryContract,
    AerodynamicsContract,
    PropulsionContract,
    TransitionContract,
    EnergyContract,
    BatteryContract,
    MassPropertiesContract,
    ComponentMassItem,
    InertiaTensorContract,
    StabilityContract,
    ControlsContract,
    PerformanceContract,
    AvionicsContract,
    ElectricalContract,
    CommercialComponentItem,
    InstallationContract,
    ManufacturingContract,
    ConstraintsContract,
    AssumptionsContract,
    CADHandoverContract,
    SimulationHandoverContract,
    ValidationStatusContract,
)
from backend.design.assembly.provenance import (
    ProvenanceCategory,
    EngineeringStatus,
    ProvenanceRecord,
)
from backend.design.assembly.fixed_wing_adapter import FixedWingDesignAdapter
from backend.design.assembly.vtol_adapter import VTOLDesignAdapter
from backend.design.assembly.universal_engine import (
    TorqWingsDesignEngine,
    UnsupportedArchitectureError,
    InvalidTechnicalRequirementsError,
    ContractValidationError,
)
from backend.design.assembly.report_generator import (
    to_dict_deterministic,
    export_design_json,
    export_design_markdown,
    generate_markdown_report,
)

__all__ = [
    "FinalAircraftDesign",
    "AircraftClass",
    "OverallDesignStatus",
    "RequirementTraceabilityItem",
    "CoordinateSystemContract",
    "GeometryContract",
    "WingGeometryContract",
    "FuselageGeometryContract",
    "BoomGeometryContract",
    "TailGeometryContract",
    "AerodynamicsContract",
    "PropulsionContract",
    "TransitionContract",
    "EnergyContract",
    "BatteryContract",
    "MassPropertiesContract",
    "ComponentMassItem",
    "InertiaTensorContract",
    "StabilityContract",
    "ControlsContract",
    "PerformanceContract",
    "AvionicsContract",
    "ElectricalContract",
    "CommercialComponentItem",
    "InstallationContract",
    "ManufacturingContract",
    "ConstraintsContract",
    "AssumptionsContract",
    "CADHandoverContract",
    "SimulationHandoverContract",
    "ValidationStatusContract",
    "ProvenanceCategory",
    "EngineeringStatus",
    "ProvenanceRecord",
    "FixedWingDesignAdapter",
    "VTOLDesignAdapter",
    "TorqWingsDesignEngine",
    "UnsupportedArchitectureError",
    "InvalidTechnicalRequirementsError",
    "ContractValidationError",
    "to_dict_deterministic",
    "export_design_json",
    "export_design_markdown",
    "generate_markdown_report",
]
