"""
Fixed-Wing Mission Profile Subsystem

Purpose:
    Defines the `MissionProfile` domain model, which represents the processed engineering interpretation
    of the mission parameters, environment, and physical characteristics.

Role in Architecture:
    `MissionProfile` is generated by the analyzer and stores both determined requirements (e.g. altitude, air density)
    and calculated engineering characteristics (e.g. energy demand, design emphases).
"""

from dataclasses import dataclass, field
from typing import Any
from backend.design.fixed_wing.mission.mission_requirements import (
    MissionCategory,
    LaunchMethod,
    LandingMethod,
    EnvironmentType,
    AutonomyLevel,
)


@dataclass(slots=True)
class MissionProfile:
    """
    Engineering-level profile of a fixed-wing aircraft mission.

    Attributes:
        mission_category (MissionCategory): Determined/validated category of the mission.
        payload_kg (float): Operational payload weight constraint in kg.
        flight_time_min (float): Target flight time (endurance) in minutes.
        cruise_speed_kmh (float): Cruise speed target in km/h.
        stall_speed_target_kmh (float | None): Target stall speed in km/h.
        maximum_takeoff_weight_limit_kg (float | None): Limit on maximum takeoff weight in kg.
        operational_altitude_m (float): Target cruise altitude in meters.
        mission_range_km (float): Required flight range in km.
        launch_method (LaunchMethod): Selected launch method.
        landing_method (LandingMethod): Selected landing/recovery method.
        budget (float | None): Budget constraints.
        environment (EnvironmentType): Operating environment.
        autonomy_level (AutonomyLevel): System autonomy level.
        
        # Engineering Physics & Analysis Characteristics
        air_density_kg_m3 (float): Standard atmosphere air density at operational altitude.
        energy_demand_kwh (float): Estimated mission energy required.
        cruise_emphasis (float): Normalized factor representing cruise importance (0.0 to 1.0).
        payload_emphasis (float): Normalized factor representing payload importance (0.0 to 1.0).
        launch_recovery_complexity (float): Normalized index for launch and recovery complexity (0.0 to 1.0).
        environmental_complexity (float): Normalized index for environmental hazards (0.0 to 1.0).
        operational_risk_score (float): Normalized assessment of operational risks (0.0 to 1.0).
        
        # Summary & Metadata
        mission_summary (str): Textual description summarizing the engineering attributes of the mission.
        metadata (dict[str, Any]): Any additional unstructured data.
    """

    mission_category: MissionCategory
    payload_kg: float
    flight_time_min: float
    cruise_speed_kmh: float
    stall_speed_target_kmh: float | None
    maximum_takeoff_weight_limit_kg: float | None
    operational_altitude_m: float
    mission_range_km: float
    launch_method: LaunchMethod
    landing_method: LandingMethod
    budget: float | None
    environment: EnvironmentType
    autonomy_level: AutonomyLevel

    # Engineering / Calculated fields (can have default initializers if needed, but normally populated in analysis)
    air_density_kg_m3: float = 1.225
    energy_demand_kwh: float = 0.0
    cruise_emphasis: float = 0.5
    payload_emphasis: float = 0.5
    launch_recovery_complexity: float = 0.5
    environmental_complexity: float = 0.5
    operational_risk_score: float = 0.5
    initial_mtow_seed_kg: float | None = None
    current_iteration_mtow_kg: float | None = None
    mission_summary: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
