"""
ReportTemplate Subsystem

Purpose:
    Defines the abstract `ReportTemplate` interface and concrete report layout templates.

Role in Architecture:
    `ReportTemplate` implements the Strategy/Template pattern to define section layout structure for
    Drone, Fixed-Wing, VTOL, and Summary reports from provided engineering artifacts.
"""

from abc import ABC, abstractmethod
from typing import Any
from backend.design.studio.artifacts.artifact import EngineeringArtifact
from backend.design.studio.reports.report_section import ReportSection


class ReportTemplate(ABC):
    """
    Abstract interface for report layout templates.
    """

    @property
    @abstractmethod
    def template_name(self) -> str:
        """Unique identifier name of the report template."""
        pass

    @abstractmethod
    def build_sections(self, artifacts: list[EngineeringArtifact]) -> list[ReportSection]:
        """
        Builds structured report sections from input engineering artifacts.

        Args:
            artifacts (list[EngineeringArtifact]): Input engineering artifacts.

        Returns:
            list[ReportSection]: Built report sections in display order.
        """
        pass


class DroneReportTemplate(ReportTemplate):
    """Report template layout for Drone / Multirotor aircraft designs."""

    @property
    def template_name(self) -> str:
        return "DroneReportTemplate"

    def build_sections(self, artifacts: list[EngineeringArtifact]) -> list[ReportSection]:
        sections: list[ReportSection] = []

        # Section 1: Executive Summary
        sections.append(
            ReportSection(
                title="1. Executive Summary",
                order=1,
                content="Multirotor aircraft engineering design report generated by Torq Wings Drone Studio.",
                artifacts=[a for a in artifacts if a.category == "MISSION"]
            )
        )

        # Section 2: Propulsion & Power System
        sections.append(
            ReportSection(
                title="2. Propulsion & Power System",
                order=2,
                content="Selected motor, ESC, propeller, and battery system specifications.",
                artifacts=[a for a in artifacts if a.category in ("MOTOR_SELECTION", "ESC_SELECTION", "BATTERY_SELECTION", "PROPELLER_SELECTION", "POWER_SYSTEM")]
            )
        )

        # Section 3: Performance & Weight Breakdown
        sections.append(
            ReportSection(
                title="3. Performance & Weight Breakdown",
                order=3,
                content="Evaluated flight endurance, range, payload capacity, and mass properties.",
                artifacts=[a for a in artifacts if a.category in ("PERFORMANCE_ANALYSIS", "WEIGHT_BREAKDOWN", "CG_ANALYSIS")]
            )
        )

        # Section 4: Validation & Engineering Scoring
        sections.append(
            ReportSection(
                title="4. Validation & Engineering Scoring",
                order=4,
                content="Engineering scoring breakdown, constraint compliance logs, and trade-off evaluation.",
                artifacts=[a for a in artifacts if a.category in ("ENGINEERING_SCORING", "VALIDATION", "OPTIMIZATION")]
            )
        )

        return sections


class FixedWingReportTemplate(ReportTemplate):
    """Report template layout for Fixed-Wing aircraft designs."""

    @property
    def template_name(self) -> str:
        return "FixedWingReportTemplate"

    def build_sections(self, artifacts: list[EngineeringArtifact]) -> list[ReportSection]:
        sections: list[ReportSection] = []

        sections.append(
            ReportSection(
                title="1. Executive Summary",
                order=1,
                content="Fixed-wing aircraft engineering design report.",
                artifacts=[a for a in artifacts if a.category == "MISSION"]
            )
        )
        sections.append(
            ReportSection(
                title="2. Aerodynamics & Wing Geometry",
                order=2,
                content="Airfoil selection, wing planform, aspect ratio, and L/D polar analysis.",
                artifacts=[a for a in artifacts if a.category in ("WING_DESIGN", "AERODYNAMIC_ANALYSIS", "TAIL_DESIGN")]
            )
        )
        sections.append(
            ReportSection(
                title="3. Propulsion & Power",
                order=3,
                content="Cruise motor, propeller, and battery energy specs.",
                artifacts=[a for a in artifacts if a.category in ("MOTOR_SELECTION", "BATTERY_SELECTION", "PROPELLER_SELECTION")]
            )
        )
        sections.append(
            ReportSection(
                title="4. Performance & Stability",
                order=4,
                content="Mass properties, CG margin, climb rate, and range calculations.",
                artifacts=[a for a in artifacts if a.category in ("PERFORMANCE_ANALYSIS", "WEIGHT_BREAKDOWN", "CG_ANALYSIS")]
            )
        )
        return sections


class VTOLReportTemplate(ReportTemplate):
    """Report template layout for VTOL aircraft designs."""

    @property
    def template_name(self) -> str:
        return "VTOLReportTemplate"

    def build_sections(self, artifacts: list[EngineeringArtifact]) -> list[ReportSection]:
        sections: list[ReportSection] = []

        sections.append(
            ReportSection(
                title="1. Executive Summary",
                order=1,
                content="VTOL hybrid aircraft engineering design report.",
                artifacts=[a for a in artifacts if a.category == "MISSION"]
            )
        )
        sections.append(
            ReportSection(
                title="2. Hover & Lift System",
                order=2,
                content="Vertical lift motor, ESC, and propeller sizing.",
                artifacts=[a for a in artifacts if a.category in ("MOTOR_SELECTION", "PROPELLER_SELECTION")]
            )
        )
        sections.append(
            ReportSection(
                title="3. Wing & Forward Flight System",
                order=3,
                content="Wing geometry, pusher propulsion, and transition aerodynamics.",
                artifacts=[a for a in artifacts if a.category in ("WING_DESIGN", "AERODYNAMIC_ANALYSIS")]
            )
        )
        sections.append(
            ReportSection(
                title="4. Mission Performance & Trade-Offs",
                order=4,
                content="Energy consumption profile across hover, transition, and cruise flight phases.",
                artifacts=[a for a in artifacts if a.category in ("PERFORMANCE_ANALYSIS", "POWER_SYSTEM", "OPTIMIZATION")]
            )
        )
        return sections


class EngineeringSummaryTemplate(ReportTemplate):
    """General summary report template."""

    @property
    def template_name(self) -> str:
        return "EngineeringSummaryTemplate"

    def build_sections(self, artifacts: list[EngineeringArtifact]) -> list[ReportSection]:
        return [
            ReportSection(
                title="1. Executive Summary",
                order=1,
                content="Summary of engineering design artifacts.",
                artifacts=list(artifacts)
            )
        ]
